### ISSUE TITLE
.EXE Level 1 Remake doesn't work

### ISSUE THREAD

**Issue by OverlordArt** [tyndyrn/Visceral-Carnage_GAME#13]
Technical Issue

When the game is complied into the .exe Level 1 Remake doesn't work at all, Level 1 normal works fine.

This might be a compiling issue that is causing it, this issue is high priority as the .exe is needed for the final assignment.

**Comment by Asas621** [comment]
Right now the game is fully playable, from beginning to end. If you get steamVR working first and then the game it works fine, but if you were to boot up oculus then the game and then steam vr it'll be messed up because its trying to use the oculus one rather than the steam one and they'll fight for control which causes the camera to cut between the two. for simplicity sake the game is fully playable and working just with that caveat for the time being.
